# Generated by Django 5.2.7 on 2025-10-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='psn_id',
            field=models.CharField(default='', max_length=17, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='retroachievements_id',
            field=models.CharField(default='', max_length=17, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='xbox_id',
            field=models.CharField(default='', max_length=17, null=True, unique=True),
        ),
    ]
