# Generated by Django 5.2.7 on 2025-10-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_psn_id_user_retroachievements_id_user_xbox_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='psn_id',
            field=models.CharField(default='', max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='retroachievements_id',
            field=models.CharField(default='', max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='steam_id',
            field=models.CharField(default='', max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='xbox_id',
            field=models.CharField(default='', max_length=17, null=True),
        ),
    ]
