# Generated by Django 5.2.7 on 2025-10-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_psn_id_alter_user_retroachievements_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='psn_id',
            field=models.CharField(blank=True, default='', max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='retroachievements_id',
            field=models.CharField(blank=True, default='', max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='steam_id',
            field=models.CharField(blank=True, default='', max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='xbox_id',
            field=models.CharField(blank=True, default='', max_length=17, null=True),
        ),
    ]
