# Generated by Django 5.2.7 on 2025-10-20 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_psn_id_alter_user_retroachievements_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='psn_id',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
